### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by Nyox**
Added italian translation.
Still missing translation for all expansions

### CODE REVIEW

**Comment by stefanseifert** [comment]
thanks a lot! - there is one key missing of one of the XOs from the base box:
`rules.difficultyLevel.veryHard.executiveOfficer.viktor-fiesler`

i've spotted some missing translations for base game rules as well (e.g. `rules.general.machineryTypeWild`, `rules.general.building`), but if you do not have translations for that at hand, i can merge it as-is.

**Comment by Nyox** [comment]
> thanks a lot! - there is one key missing of one of the XOs from the base box: `rules.difficultyLevel.veryHard.executiveOfficer.viktor-fiesler`
> 
> i've spotted some missing translations for base game rules as well (e.g. `rules.general.machineryTypeWild`, `rules.general.building`), but if you do not have translations for that at hand, i can merge it as-is.

Whoops, I'll fix them right away! Thank you

**Comment by stefanseifert** [comment]
thanks, released as v1.1.5

**Comment by Nyox** [comment]
sorry for the more errors you had to fix :)

**Pull request merged**
